name: Output Dockerfile

on: [push]

jobs:
  output-dockerfile:
    runs-on: ubuntu-18.04
    outputs:
      server-df: ${{steps.build-server-df.server-df}}
    steps:
      - name: Output Dockerfile
        id: build-server-df
        uses: ChristopherDurand/build-node-postgres-react-action@v7
        with:
          build-type: npmNodeReact
        outputs:
          server-df:
            description: "dockerfile output"

  echo-dockerfile:
    needs: output-dockerfile
    runs-on: ubuntu-18.04
    steps:
      - name: Echo Dockerfile
        run: echo ${{needs.output-dockerfile.outputs.server-df }}
