name: learn-build-and-push-docker
on: [pull_request]
jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: request_bin_docker_build_1
        uses: docker/build-push-actions@v2
        with:
          push: true
          tags: mhlim/request-bin:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
