name: SSH test

on: [push]

jobs:
  access_droplet:
    runs-on: ubuntu-18.04
    steps:
      - name: Executing remote script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            pwd
            ls
          